<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>mikeio-examples – dfs0_-_cmems_insitu</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">mikeio-examples</span>
  </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html">Home</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../search.html">Search</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../contributing.html">Contributing</a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#dfs0---cmems-in-situ-data" id="toc-dfs0---cmems-in-situ-data" class="nav-link active" data-scroll-target="#dfs0---cmems-in-situ-data">Dfs0 - CMEMS <em>in-situ</em> data</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">



<section id="dfs0---cmems-in-situ-data" class="level1">
<h1>Dfs0 - CMEMS <em>in-situ</em> data</h1>
<div class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> xarray <span class="im">as</span> xr</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> mikeio</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>fino <span class="op">=</span> xr.open_dataset(<span class="st">"../tests/testdata/NO_TS_MO_FINO1_202209.nc"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>fino</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="3">

<div><svg style="position: absolute; width: 0; height: 0; overflow: hidden">
<defs>
<symbol id="icon-database" viewbox="0 0 32 32">
<path d="M16 0c-8.837 0-16 2.239-16 5v4c0 2.761 7.163 5 16 5s16-2.239 16-5v-4c0-2.761-7.163-5-16-5z"></path>
<path d="M16 17c-8.837 0-16-2.239-16-5v6c0 2.761 7.163 5 16 5s16-2.239 16-5v-6c0 2.761-7.163 5-16 5z"></path>
<path d="M16 26c-8.837 0-16-2.239-16-5v6c0 2.761 7.163 5 16 5s16-2.239 16-5v-6c0 2.761-7.163 5-16 5z"></path>
</symbol>
<symbol id="icon-file-text2" viewbox="0 0 32 32">
<path d="M28.681 7.159c-0.694-0.947-1.662-2.053-2.724-3.116s-2.169-2.030-3.116-2.724c-1.612-1.182-2.393-1.319-2.841-1.319h-15.5c-1.378 0-2.5 1.121-2.5 2.5v27c0 1.378 1.122 2.5 2.5 2.5h23c1.378 0 2.5-1.122 2.5-2.5v-19.5c0-0.448-0.137-1.23-1.319-2.841zM24.543 5.457c0.959 0.959 1.712 1.825 2.268 2.543h-4.811v-4.811c0.718 0.556 1.584 1.309 2.543 2.268zM28 29.5c0 0.271-0.229 0.5-0.5 0.5h-23c-0.271 0-0.5-0.229-0.5-0.5v-27c0-0.271 0.229-0.5 0.5-0.5 0 0 15.499-0 15.5 0v7c0 0.552 0.448 1 1 1h7v19.5z"></path>
<path d="M23 26h-14c-0.552 0-1-0.448-1-1s0.448-1 1-1h14c0.552 0 1 0.448 1 1s-0.448 1-1 1z"></path>
<path d="M23 22h-14c-0.552 0-1-0.448-1-1s0.448-1 1-1h14c0.552 0 1 0.448 1 1s-0.448 1-1 1z"></path>
<path d="M23 18h-14c-0.552 0-1-0.448-1-1s0.448-1 1-1h14c0.552 0 1 0.448 1 1s-0.448 1-1 1z"></path>
</symbol>
</defs>
</svg>
<style>/* CSS stylesheet for displaying xarray objects in jupyterlab.
 *
 */

:root {
  --xr-font-color0: var(--jp-content-font-color0, rgba(0, 0, 0, 1));
  --xr-font-color2: var(--jp-content-font-color2, rgba(0, 0, 0, 0.54));
  --xr-font-color3: var(--jp-content-font-color3, rgba(0, 0, 0, 0.38));
  --xr-border-color: var(--jp-border-color2, #e0e0e0);
  --xr-disabled-color: var(--jp-layout-color3, #bdbdbd);
  --xr-background-color: var(--jp-layout-color0, white);
  --xr-background-color-row-even: var(--jp-layout-color1, white);
  --xr-background-color-row-odd: var(--jp-layout-color2, #eeeeee);
}

html[theme=dark],
body[data-theme=dark],
body.vscode-dark {
  --xr-font-color0: rgba(255, 255, 255, 1);
  --xr-font-color2: rgba(255, 255, 255, 0.54);
  --xr-font-color3: rgba(255, 255, 255, 0.38);
  --xr-border-color: #1F1F1F;
  --xr-disabled-color: #515151;
  --xr-background-color: #111111;
  --xr-background-color-row-even: #111111;
  --xr-background-color-row-odd: #313131;
}

.xr-wrap {
  display: block !important;
  min-width: 300px;
  max-width: 700px;
}

.xr-text-repr-fallback {
  /* fallback to plain text repr when CSS is not injected (untrusted notebook) */
  display: none;
}

.xr-header {
  padding-top: 6px;
  padding-bottom: 6px;
  margin-bottom: 4px;
  border-bottom: solid 1px var(--xr-border-color);
}

.xr-header > div,
.xr-header > ul {
  display: inline;
  margin-top: 0;
  margin-bottom: 0;
}

.xr-obj-type,
.xr-array-name {
  margin-left: 2px;
  margin-right: 10px;
}

.xr-obj-type {
  color: var(--xr-font-color2);
}

.xr-sections {
  padding-left: 0 !important;
  display: grid;
  grid-template-columns: 150px auto auto 1fr 20px 20px;
}

.xr-section-item {
  display: contents;
}

.xr-section-item input {
  display: none;
}

.xr-section-item input + label {
  color: var(--xr-disabled-color);
}

.xr-section-item input:enabled + label {
  cursor: pointer;
  color: var(--xr-font-color2);
}

.xr-section-item input:enabled + label:hover {
  color: var(--xr-font-color0);
}

.xr-section-summary {
  grid-column: 1;
  color: var(--xr-font-color2);
  font-weight: 500;
}

.xr-section-summary > span {
  display: inline-block;
  padding-left: 0.5em;
}

.xr-section-summary-in:disabled + label {
  color: var(--xr-font-color2);
}

.xr-section-summary-in + label:before {
  display: inline-block;
  content: '►';
  font-size: 11px;
  width: 15px;
  text-align: center;
}

.xr-section-summary-in:disabled + label:before {
  color: var(--xr-disabled-color);
}

.xr-section-summary-in:checked + label:before {
  content: '▼';
}

.xr-section-summary-in:checked + label > span {
  display: none;
}

.xr-section-summary,
.xr-section-inline-details {
  padding-top: 4px;
  padding-bottom: 4px;
}

.xr-section-inline-details {
  grid-column: 2 / -1;
}

.xr-section-details {
  display: none;
  grid-column: 1 / -1;
  margin-bottom: 5px;
}

.xr-section-summary-in:checked ~ .xr-section-details {
  display: contents;
}

.xr-array-wrap {
  grid-column: 1 / -1;
  display: grid;
  grid-template-columns: 20px auto;
}

.xr-array-wrap > label {
  grid-column: 1;
  vertical-align: top;
}

.xr-preview {
  color: var(--xr-font-color3);
}

.xr-array-preview,
.xr-array-data {
  padding: 0 5px !important;
  grid-column: 2;
}

.xr-array-data,
.xr-array-in:checked ~ .xr-array-preview {
  display: none;
}

.xr-array-in:checked ~ .xr-array-data,
.xr-array-preview {
  display: inline-block;
}

.xr-dim-list {
  display: inline-block !important;
  list-style: none;
  padding: 0 !important;
  margin: 0;
}

.xr-dim-list li {
  display: inline-block;
  padding: 0;
  margin: 0;
}

.xr-dim-list:before {
  content: '(';
}

.xr-dim-list:after {
  content: ')';
}

.xr-dim-list li:not(:last-child):after {
  content: ',';
  padding-right: 5px;
}

.xr-has-index {
  font-weight: bold;
}

.xr-var-list,
.xr-var-item {
  display: contents;
}

.xr-var-item > div,
.xr-var-item label,
.xr-var-item > .xr-var-name span {
  background-color: var(--xr-background-color-row-even);
  margin-bottom: 0;
}

.xr-var-item > .xr-var-name:hover span {
  padding-right: 5px;
}

.xr-var-list > li:nth-child(odd) > div,
.xr-var-list > li:nth-child(odd) > label,
.xr-var-list > li:nth-child(odd) > .xr-var-name span {
  background-color: var(--xr-background-color-row-odd);
}

.xr-var-name {
  grid-column: 1;
}

.xr-var-dims {
  grid-column: 2;
}

.xr-var-dtype {
  grid-column: 3;
  text-align: right;
  color: var(--xr-font-color2);
}

.xr-var-preview {
  grid-column: 4;
}

.xr-var-name,
.xr-var-dims,
.xr-var-dtype,
.xr-preview,
.xr-attrs dt {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  padding-right: 10px;
}

.xr-var-name:hover,
.xr-var-dims:hover,
.xr-var-dtype:hover,
.xr-attrs dt:hover {
  overflow: visible;
  width: auto;
  z-index: 1;
}

.xr-var-attrs,
.xr-var-data {
  display: none;
  background-color: var(--xr-background-color) !important;
  padding-bottom: 5px !important;
}

.xr-var-attrs-in:checked ~ .xr-var-attrs,
.xr-var-data-in:checked ~ .xr-var-data {
  display: block;
}

.xr-var-data > table {
  float: right;
}

.xr-var-name span,
.xr-var-data,
.xr-attrs {
  padding-left: 25px !important;
}

.xr-attrs,
.xr-var-attrs,
.xr-var-data {
  grid-column: 1 / -1;
}

dl.xr-attrs {
  padding: 0;
  margin: 0;
  display: grid;
  grid-template-columns: 125px auto;
}

.xr-attrs dt,
.xr-attrs dd {
  padding: 0;
  margin: 0;
  float: left;
  padding-right: 10px;
  width: auto;
}

.xr-attrs dt {
  font-weight: normal;
  grid-column: 1;
}

.xr-attrs dt:hover span {
  display: inline-block;
  background: var(--xr-background-color);
  padding-right: 10px;
}

.xr-attrs dd {
  grid-column: 2;
  white-space: pre-wrap;
  word-break: break-all;
}

.xr-icon-database,
.xr-icon-file-text2 {
  display: inline-block;
  vertical-align: middle;
  width: 1em;
  height: 1.5em !important;
  stroke-width: 0;
  stroke: currentColor;
  fill: currentColor;
}
</style><pre class="xr-text-repr-fallback">&lt;xarray.Dataset&gt;
Dimensions:      (TIME: 2879, LATITUDE: 2879, LONGITUDE: 2879, DEPTH: 7,
                  POSITION: 2879)
Coordinates:
  * TIME         (TIME) datetime64[ns] 2022-09-01 ... 2022-09-30T23:31:59.999...
  * LATITUDE     (LATITUDE) float32 54.0 54.0 54.0 54.0 ... 54.0 54.0 54.0 54.0
  * LONGITUDE    (LONGITUDE) float32 6.583 6.583 6.583 ... 6.583 6.583 6.583
    DEPH         (TIME, DEPTH) float32 0.0 0.5 3.0 6.0 ... 6.0 10.0 15.0 25.0
Dimensions without coordinates: DEPTH, POSITION
Data variables: (12/22)
    DEPH_QC      (TIME, DEPTH) float32 7.0 7.0 7.0 7.0 7.0 ... 7.0 7.0 7.0 7.0
    TIME_QC      (TIME) float32 1.0 1.0 1.0 1.0 1.0 1.0 ... 1.0 1.0 1.0 1.0 1.0
    POSITION_QC  (POSITION) float32 7.0 7.0 7.0 7.0 7.0 ... 7.0 7.0 7.0 7.0 7.0
    TEMP         (TIME, DEPTH) float64 nan nan nan nan nan ... nan nan nan nan
    TEMP_QC      (TIME, DEPTH) float32 nan 9.0 9.0 9.0 9.0 ... 9.0 9.0 9.0 9.0
    VHM0         (TIME, DEPTH) float64 nan nan nan nan nan ... nan nan nan nan
    ...           ...
    VTPK_DM      (TIME, DEPTH) object nan nan nan nan nan ... nan nan nan nan
    VTZA         (TIME, DEPTH) float64 4.12 nan nan nan nan ... nan nan nan nan
    VTZA_QC      (TIME, DEPTH) float32 1.0 nan nan nan nan ... nan nan nan nan
    VPED         (TIME, DEPTH) float64 nan nan nan nan nan ... nan nan nan nan
    VPED_QC      (TIME, DEPTH) float32 9.0 nan nan nan nan ... nan nan nan nan
    VPED_DM      (TIME, DEPTH) object nan nan nan nan nan ... nan nan nan nan
Attributes: (12/46)
    platform_code:                  FINO1
    platform_name:                  
    data_mode:                      M
    title:                          NWS - NRT in situ Observations
    summary:                        Oceanographic data from North West Shelf
    naming_authority:               Copernicus Marine In Situ
    ...                             ...
    doi:                            
    pi_name:                        
    qc_manual:                      OceanSITES User's Manual v1.2
    date_update:                    2022-10-07T05:39:40Z
    history:                        2022-10-01T18:04:25Z : Creation; 2022-10-...
    wmo_inst_type:                  </pre><div class="xr-wrap" style="display:none"><div class="xr-header"><div class="xr-obj-type">xarray.Dataset</div></div><ul class="xr-sections"><li class="xr-section-item"><input id="section-dd554f57-153f-4538-bee6-6fa83e8e7f50" class="xr-section-summary-in" type="checkbox" disabled=""><label for="section-dd554f57-153f-4538-bee6-6fa83e8e7f50" class="xr-section-summary" title="Expand/collapse section">Dimensions:</label><div class="xr-section-inline-details"><ul class="xr-dim-list"><li><span class="xr-has-index">TIME</span>: 2879</li><li><span class="xr-has-index">LATITUDE</span>: 2879</li><li><span class="xr-has-index">LONGITUDE</span>: 2879</li><li><span>DEPTH</span>: 7</li><li><span>POSITION</span>: 2879</li></ul></div><div class="xr-section-details"></div></li><li class="xr-section-item"><input id="section-b6cc143d-c9f3-498e-9b29-8fc45ae08b5e" class="xr-section-summary-in" type="checkbox" checked=""><label for="section-b6cc143d-c9f3-498e-9b29-8fc45ae08b5e" class="xr-section-summary">Coordinates: <span>(4)</span></label><div class="xr-section-inline-details"></div><div class="xr-section-details"><ul class="xr-var-list"><li class="xr-var-item"><div class="xr-var-name"><span class="xr-has-index">TIME</span></div><div class="xr-var-dims">(TIME)</div><div class="xr-var-dtype">datetime64[ns]</div><div class="xr-var-preview xr-preview">2022-09-01 ... 2022-09-30T23:31:...</div><input id="attrs-cbbd0d06-d4ee-498d-ae0e-9964b834c18a" class="xr-var-attrs-in" type="checkbox"><label for="attrs-cbbd0d06-d4ee-498d-ae0e-9964b834c18a" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-f9d33073-3890-4c7a-9924-3ef6e0653526" class="xr-var-data-in" type="checkbox"><label for="data-f9d33073-3890-4c7a-9924-3ef6e0653526" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>Time</dd><dt><span>standard_name :</span></dt><dd>time</dd><dt><span>valid_min :</span></dt><dd>-90000.0</dd><dt><span>valid_max :</span></dt><dd>90000.0</dd><dt><span>uncertainty :</span></dt><dd> </dd><dt><span>comment :</span></dt><dd> </dd><dt><span>axis :</span></dt><dd>T</dd><dt><span>ancillary_variables :</span></dt><dd>TIME_QC</dd></dl></div><div class="xr-var-data"><pre>array(['2022-09-01T00:00:00.000000000', '2022-09-01T00:02:00.000000000',
       '2022-09-01T00:30:00.000000000', ..., '2022-09-30T23:02:00.000000000',
       '2022-09-30T23:30:00.000000000', '2022-09-30T23:31:59.999999744'],
      dtype='datetime64[ns]')</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span class="xr-has-index">LATITUDE</span></div><div class="xr-var-dims">(LATITUDE)</div><div class="xr-var-dtype">float32</div><div class="xr-var-preview xr-preview">54.0 54.0 54.0 ... 54.0 54.0 54.0</div><input id="attrs-c6ed9708-5997-4495-bb7b-99bd97853eaa" class="xr-var-attrs-in" type="checkbox"><label for="attrs-c6ed9708-5997-4495-bb7b-99bd97853eaa" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-89f8c862-a601-432e-b264-73b24b0179df" class="xr-var-data-in" type="checkbox"><label for="data-89f8c862-a601-432e-b264-73b24b0179df" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>Latitude of each location</dd><dt><span>standard_name :</span></dt><dd>latitude</dd><dt><span>units :</span></dt><dd>degree_north</dd><dt><span>valid_min :</span></dt><dd>-90.0</dd><dt><span>valid_max :</span></dt><dd>90.0</dd><dt><span>uncertainty :</span></dt><dd></dd><dt><span>comment :</span></dt><dd></dd><dt><span>axis :</span></dt><dd>Y</dd><dt><span>ancillary_variables :</span></dt><dd>POSITION_QC</dd></dl></div><div class="xr-var-data"><pre>array([54., 54., 54., ..., 54., 54., 54.], dtype=float32)</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span class="xr-has-index">LONGITUDE</span></div><div class="xr-var-dims">(LONGITUDE)</div><div class="xr-var-dtype">float32</div><div class="xr-var-preview xr-preview">6.583 6.583 6.583 ... 6.583 6.583</div><input id="attrs-f09a343b-923a-47f3-b36a-5919c98d10c1" class="xr-var-attrs-in" type="checkbox"><label for="attrs-f09a343b-923a-47f3-b36a-5919c98d10c1" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-210fb96e-f8be-4d9e-b965-a6274933d4d3" class="xr-var-data-in" type="checkbox"><label for="data-210fb96e-f8be-4d9e-b965-a6274933d4d3" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>Longitude of each location</dd><dt><span>standard_name :</span></dt><dd>longitude</dd><dt><span>units :</span></dt><dd>degree_east</dd><dt><span>valid_min :</span></dt><dd>-180.0</dd><dt><span>valid_max :</span></dt><dd>180.0</dd><dt><span>uncertainty :</span></dt><dd></dd><dt><span>comment :</span></dt><dd></dd><dt><span>axis :</span></dt><dd>X</dd><dt><span>ancillary_variables :</span></dt><dd>POSITION_QC</dd></dl></div><div class="xr-var-data"><pre>array([6.583333, 6.583333, 6.583333, ..., 6.583333, 6.583333, 6.583333],
      dtype=float32)</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>DEPH</span></div><div class="xr-var-dims">(TIME, DEPTH)</div><div class="xr-var-dtype">float32</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-9166f21e-73eb-49bf-9f30-882050e0c165" class="xr-var-attrs-in" type="checkbox"><label for="attrs-9166f21e-73eb-49bf-9f30-882050e0c165" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-a45720b5-5064-40de-822e-8a87b1dff0a9" class="xr-var-data-in" type="checkbox"><label for="data-a45720b5-5064-40de-822e-8a87b1dff0a9" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>Depth</dd><dt><span>standard_name :</span></dt><dd>depth</dd><dt><span>units :</span></dt><dd>m</dd><dt><span>positive :</span></dt><dd>down</dd><dt><span>valid_min :</span></dt><dd>-12000.0</dd><dt><span>valid_max :</span></dt><dd>12000.0</dd><dt><span>uncertainty :</span></dt><dd></dd><dt><span>comment :</span></dt><dd></dd><dt><span>axis :</span></dt><dd>Z</dd><dt><span>reference :</span></dt><dd>sea_level</dd><dt><span>data_mode :</span></dt><dd>R</dd><dt><span>ancillary_variables :</span></dt><dd>DEPH_QC</dd></dl></div><div class="xr-var-data"><pre>array([[ 0. ,  0.5,  3. , ..., 10. , 15. , 25. ],
       [ 0. ,  0.5,  3. , ..., 10. , 15. , 25. ],
       [ 0. ,  0.5,  3. , ..., 10. , 15. , 25. ],
       ...,
       [ 0. ,  0.5,  3. , ..., 10. , 15. , 25. ],
       [ 0. ,  0.5,  3. , ..., 10. , 15. , 25. ],
       [ 0. ,  0.5,  3. , ..., 10. , 15. , 25. ]], dtype=float32)</pre></div></li></ul></div></li><li class="xr-section-item"><input id="section-1a77e710-d495-4f88-ac0b-f06319f570aa" class="xr-section-summary-in" type="checkbox"><label for="section-1a77e710-d495-4f88-ac0b-f06319f570aa" class="xr-section-summary">Data variables: <span>(22)</span></label><div class="xr-section-inline-details"></div><div class="xr-section-details"><ul class="xr-var-list"><li class="xr-var-item"><div class="xr-var-name"><span>DEPH_QC</span></div><div class="xr-var-dims">(TIME, DEPTH)</div><div class="xr-var-dtype">float32</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-7a56749b-66fc-42f9-8588-fee5e5ee7578" class="xr-var-attrs-in" type="checkbox"><label for="attrs-7a56749b-66fc-42f9-8588-fee5e5ee7578" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-c7c18259-82ad-4152-91a6-6b269cf6c672" class="xr-var-data-in" type="checkbox"><label for="data-c7c18259-82ad-4152-91a6-6b269cf6c672" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>Depth quality flag</dd><dt><span>conventions :</span></dt><dd>Copernicus Marine In Situ reference table 2</dd><dt><span>valid_min :</span></dt><dd>0</dd><dt><span>valid_max :</span></dt><dd>9</dd><dt><span>flag_values :</span></dt><dd>[0 1 2 3 4 5 6 7 8 9]</dd><dt><span>flag_meanings :</span></dt><dd>no_qc_performed good_data probably_good_data bad_data_that_are_potentially_correctable bad_data value_changed value_below_detection nominal_value interpolated_value missing_value</dd></dl></div><div class="xr-var-data"><pre>array([[7., 7., 7., ..., 7., 7., 7.],
       [7., 7., 7., ..., 7., 7., 7.],
       [7., 7., 7., ..., 7., 7., 7.],
       ...,
       [7., 7., 7., ..., 7., 7., 7.],
       [7., 7., 7., ..., 7., 7., 7.],
       [7., 7., 7., ..., 7., 7., 7.]], dtype=float32)</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>TIME_QC</span></div><div class="xr-var-dims">(TIME)</div><div class="xr-var-dtype">float32</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-0de6e564-d324-4aae-92fa-f20330a62465" class="xr-var-attrs-in" type="checkbox"><label for="attrs-0de6e564-d324-4aae-92fa-f20330a62465" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-7e93285a-7bd8-4e8a-99b9-d69916b9efee" class="xr-var-data-in" type="checkbox"><label for="data-7e93285a-7bd8-4e8a-99b9-d69916b9efee" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>Time quality flag</dd><dt><span>conventions :</span></dt><dd>Copernicus Marine In Situ reference table 2</dd><dt><span>valid_min :</span></dt><dd>0</dd><dt><span>valid_max :</span></dt><dd>9</dd><dt><span>flag_values :</span></dt><dd>[0 1 2 3 4 5 6 7 8 9]</dd><dt><span>flag_meanings :</span></dt><dd>no_qc_performed good_data probably_good_data bad_data_that_are_potentially_correctable bad_data value_changed value_below_detection nominal_value interpolated_value missing_value</dd></dl></div><div class="xr-var-data"><pre>array([1., 1., 1., ..., 1., 1., 1.], dtype=float32)</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>POSITION_QC</span></div><div class="xr-var-dims">(POSITION)</div><div class="xr-var-dtype">float32</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-4968cd37-dc1b-4db3-a0f4-b7786d70fc3a" class="xr-var-attrs-in" type="checkbox"><label for="attrs-4968cd37-dc1b-4db3-a0f4-b7786d70fc3a" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-85799fa5-db78-4867-af88-e75011a7db89" class="xr-var-data-in" type="checkbox"><label for="data-85799fa5-db78-4867-af88-e75011a7db89" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>Position quality flag</dd><dt><span>conventions :</span></dt><dd>Copernicus Marine In Situ reference table 2</dd><dt><span>valid_min :</span></dt><dd>0</dd><dt><span>valid_max :</span></dt><dd>9</dd><dt><span>flag_values :</span></dt><dd>[0 1 2 3 4 5 6 7 8 9]</dd><dt><span>flag_meanings :</span></dt><dd>no_qc_performed good_data probably_good_data bad_data_that_are_potentially_correctable bad_data value_changed value_below_detection nominal_value interpolated_value missing_value</dd></dl></div><div class="xr-var-data"><pre>array([7., 7., 7., ..., 7., 7., 7.], dtype=float32)</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>TEMP</span></div><div class="xr-var-dims">(TIME, DEPTH)</div><div class="xr-var-dtype">float64</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-fdd0cdb2-c79a-404e-b261-ef23d4a8ee48" class="xr-var-attrs-in" type="checkbox"><label for="attrs-fdd0cdb2-c79a-404e-b261-ef23d4a8ee48" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-3ed0adcf-0299-4a19-8845-3359b33f2860" class="xr-var-data-in" type="checkbox"><label for="data-3ed0adcf-0299-4a19-8845-3359b33f2860" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>standard_name :</span></dt><dd>sea_water_temperature</dd><dt><span>units :</span></dt><dd>degrees_C</dd><dt><span>long_name :</span></dt><dd>Sea temperature</dd><dt><span>valid_min :</span></dt><dd>-2000</dd><dt><span>valid_max :</span></dt><dd>32000</dd><dt><span>comment :</span></dt><dd> </dd><dt><span>uncertainty :</span></dt><dd> </dd><dt><span>accuracy :</span></dt><dd> </dd><dt><span>precision :</span></dt><dd> </dd><dt><span>resolution :</span></dt><dd> </dd><dt><span>cell_methods :</span></dt><dd> </dd><dt><span>sensor_depth :</span></dt><dd>0.0</dd><dt><span>sensor_mount :</span></dt><dd> </dd><dt><span>sensor_orientation :</span></dt><dd> </dd><dt><span>data_mode :</span></dt><dd>R</dd><dt><span>ancillary_variables :</span></dt><dd>TEMP_QC</dd></dl></div><div class="xr-var-data"><pre>array([[      nan,       nan,       nan, ...,       nan,       nan,       nan],
       [      nan, 19.400001,       nan, ...,       nan,       nan,       nan],
       [      nan,       nan,       nan, ...,       nan,       nan,       nan],
       ...,
       [      nan, 16.950001,       nan, ...,       nan,       nan,       nan],
       [      nan,       nan,       nan, ...,       nan,       nan,       nan],
       [      nan, 16.950001,       nan, ...,       nan,       nan,       nan]])</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>TEMP_QC</span></div><div class="xr-var-dims">(TIME, DEPTH)</div><div class="xr-var-dtype">float32</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-9de006a3-0fa9-484d-96f0-b267e72f0b1a" class="xr-var-attrs-in" type="checkbox"><label for="attrs-9de006a3-0fa9-484d-96f0-b267e72f0b1a" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-09e31a3b-e42e-4cd7-940e-76d48436e79c" class="xr-var-data-in" type="checkbox"><label for="data-09e31a3b-e42e-4cd7-940e-76d48436e79c" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>Sea temperature quality flag</dd><dt><span>conventions :</span></dt><dd>Copernicus Marine In Situ reference table 2</dd><dt><span>valid_min :</span></dt><dd>0</dd><dt><span>valid_max :</span></dt><dd>9</dd><dt><span>flag_values :</span></dt><dd>[0 1 2 3 4 5 6 7 8 9]</dd><dt><span>flag_meanings :</span></dt><dd>no_qc_performed good_data probably_good_data bad_data_that_are_potentially_correctable bad_data value_changed value_below_detection nominal_value interpolated_value missing_value</dd></dl></div><div class="xr-var-data"><pre>array([[nan,  9.,  9., ...,  9.,  9.,  9.],
       [nan,  1.,  9., ...,  9.,  9.,  9.],
       [nan,  9.,  9., ...,  9.,  9.,  9.],
       ...,
       [nan,  1.,  9., ...,  9.,  9.,  9.],
       [nan,  9.,  9., ...,  9.,  9.,  9.],
       [nan,  1.,  9., ...,  9.,  9.,  9.]], dtype=float32)</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>VHM0</span></div><div class="xr-var-dims">(TIME, DEPTH)</div><div class="xr-var-dtype">float64</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-ec67275d-e232-47d6-affc-9564cb60d451" class="xr-var-attrs-in" type="checkbox"><label for="attrs-ec67275d-e232-47d6-affc-9564cb60d451" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-ea3d1346-3faf-4fa0-9e7e-102a13c634cd" class="xr-var-data-in" type="checkbox"><label for="data-ea3d1346-3faf-4fa0-9e7e-102a13c634cd" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>standard_name :</span></dt><dd>sea_surface_wave_significant_height</dd><dt><span>units :</span></dt><dd>m</dd><dt><span>long_name :</span></dt><dd>Spectral significant wave height (Hm0)</dd><dt><span>valid_min :</span></dt><dd>1</dd><dt><span>valid_max :</span></dt><dd>25000</dd><dt><span>comment :</span></dt><dd> </dd><dt><span>uncertainty :</span></dt><dd> </dd><dt><span>accuracy :</span></dt><dd> </dd><dt><span>precision :</span></dt><dd> </dd><dt><span>resolution :</span></dt><dd> </dd><dt><span>cell_methods :</span></dt><dd> </dd><dt><span>type_of_analysis :</span></dt><dd>spectral analysis</dd><dt><span>sensor_depth :</span></dt><dd>0.0</dd><dt><span>sensor_mount :</span></dt><dd> </dd><dt><span>sensor_orientation :</span></dt><dd> </dd><dt><span>data_mode :</span></dt><dd>M</dd><dt><span>ancillary_variables :</span></dt><dd>VHM0_QC VHM0_DM</dd></dl></div><div class="xr-var-data"><pre>array([[ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [1.11,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       ...,
       [2.41,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [2.51,  nan,  nan, ...,  nan,  nan,  nan]])</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>VHM0_QC</span></div><div class="xr-var-dims">(TIME, DEPTH)</div><div class="xr-var-dtype">float32</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-af5727b6-3d03-441c-8fe1-9f61725cb0f5" class="xr-var-attrs-in" type="checkbox"><label for="attrs-af5727b6-3d03-441c-8fe1-9f61725cb0f5" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-eebd4b0a-2d83-42a2-a02a-15d3638f7c81" class="xr-var-data-in" type="checkbox"><label for="data-eebd4b0a-2d83-42a2-a02a-15d3638f7c81" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>Spectral significant wave height (Hm0) quality flag</dd><dt><span>conventions :</span></dt><dd>Copernicus Marine In Situ reference table 2</dd><dt><span>valid_min :</span></dt><dd>0</dd><dt><span>valid_max :</span></dt><dd>9</dd><dt><span>flag_values :</span></dt><dd>[0 1 2 3 4 5 6 7 8 9]</dd><dt><span>flag_meanings :</span></dt><dd>no_qc_performed good_data probably_good_data bad_data_that_are_potentially_correctable bad_data value_changed value_below_detection nominal_value interpolated_value missing_value</dd></dl></div><div class="xr-var-data"><pre>array([[ 9., nan, nan, ..., nan, nan, nan],
       [ 1., nan, nan, ..., nan, nan, nan],
       [ 9., nan, nan, ..., nan, nan, nan],
       ...,
       [ 1., nan, nan, ..., nan, nan, nan],
       [ 9., nan, nan, ..., nan, nan, nan],
       [ 1., nan, nan, ..., nan, nan, nan]], dtype=float32)</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>VHM0_DM</span></div><div class="xr-var-dims">(TIME, DEPTH)</div><div class="xr-var-dtype">object</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-8f2122b9-dab0-4b27-8846-e1971b9ac8a0" class="xr-var-attrs-in" type="checkbox"><label for="attrs-8f2122b9-dab0-4b27-8846-e1971b9ac8a0" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-bb736462-dc27-4503-88f9-5bd7734b5aba" class="xr-var-data-in" type="checkbox"><label for="data-bb736462-dc27-4503-88f9-5bd7734b5aba" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>Spectral significant wave height (Hm0) method of data processing</dd><dt><span>conventions :</span></dt><dd>Copernicus Marine In Situ reference table 1</dd><dt><span>flag_values :</span></dt><dd>R, A, D</dd><dt><span>flag_meanings :</span></dt><dd>real-time adjusted-in-real-time delayed-mode</dd></dl></div><div class="xr-var-data"><pre>array([[nan, nan, nan, ..., nan, nan, nan],
       [b'R', nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [b'R', nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [b'R', nan, nan, ..., nan, nan, nan]], dtype=object)</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>VZMX</span></div><div class="xr-var-dims">(TIME, DEPTH)</div><div class="xr-var-dtype">float64</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-1f22d9ae-435a-4eab-8c7f-b06aeb19304e" class="xr-var-attrs-in" type="checkbox"><label for="attrs-1f22d9ae-435a-4eab-8c7f-b06aeb19304e" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-4bb99c54-2b8e-4282-8b78-d1f975801da5" class="xr-var-data-in" type="checkbox"><label for="data-4bb99c54-2b8e-4282-8b78-d1f975801da5" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>standard_name :</span></dt><dd>sea_surface_wave_maximum_height</dd><dt><span>units :</span></dt><dd>m</dd><dt><span>long_name :</span></dt><dd>Maximum zero crossing wave height (Hmax)</dd><dt><span>valid_min :</span></dt><dd>0</dd><dt><span>valid_max :</span></dt><dd>40000</dd><dt><span>comment :</span></dt><dd> </dd><dt><span>uncertainty :</span></dt><dd> </dd><dt><span>accuracy :</span></dt><dd> </dd><dt><span>precision :</span></dt><dd> </dd><dt><span>resolution :</span></dt><dd> </dd><dt><span>cell_methods :</span></dt><dd> </dd><dt><span>type_of_analysis :</span></dt><dd>zero crossing</dd><dt><span>sensor_depth :</span></dt><dd>0.0</dd><dt><span>sensor_mount :</span></dt><dd> </dd><dt><span>sensor_orientation :</span></dt><dd> </dd><dt><span>data_mode :</span></dt><dd>M</dd><dt><span>ancillary_variables :</span></dt><dd>VZMX_QC VZMX_DM</dd></dl></div><div class="xr-var-data"><pre>array([[1.71,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [1.77,  nan,  nan, ...,  nan,  nan,  nan],
       ...,
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [4.19,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan]])</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>VZMX_QC</span></div><div class="xr-var-dims">(TIME, DEPTH)</div><div class="xr-var-dtype">float32</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-654366ad-9d23-4bff-b77c-e4ac0956f25d" class="xr-var-attrs-in" type="checkbox"><label for="attrs-654366ad-9d23-4bff-b77c-e4ac0956f25d" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-f5eab934-0e11-4731-8ec5-fad9a381c7ac" class="xr-var-data-in" type="checkbox"><label for="data-f5eab934-0e11-4731-8ec5-fad9a381c7ac" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>Maximum zero crossing wave height (Hmax) quality flag</dd><dt><span>conventions :</span></dt><dd>Copernicus Marine In Situ reference table 2</dd><dt><span>valid_min :</span></dt><dd>0</dd><dt><span>valid_max :</span></dt><dd>9</dd><dt><span>flag_values :</span></dt><dd>[0 1 2 3 4 5 6 7 8 9]</dd><dt><span>flag_meanings :</span></dt><dd>no_qc_performed good_data probably_good_data bad_data_that_are_potentially_correctable bad_data value_changed value_below_detection nominal_value interpolated_value missing_value</dd></dl></div><div class="xr-var-data"><pre>array([[ 1., nan, nan, ..., nan, nan, nan],
       [ 9., nan, nan, ..., nan, nan, nan],
       [ 1., nan, nan, ..., nan, nan, nan],
       ...,
       [ 9., nan, nan, ..., nan, nan, nan],
       [ 1., nan, nan, ..., nan, nan, nan],
       [ 9., nan, nan, ..., nan, nan, nan]], dtype=float32)</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>VZMX_DM</span></div><div class="xr-var-dims">(TIME, DEPTH)</div><div class="xr-var-dtype">object</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-85c82756-11a8-4432-94dc-a2a269d16581" class="xr-var-attrs-in" type="checkbox"><label for="attrs-85c82756-11a8-4432-94dc-a2a269d16581" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-4be7ea41-b3be-414e-947c-0378a762d062" class="xr-var-data-in" type="checkbox"><label for="data-4be7ea41-b3be-414e-947c-0378a762d062" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>Maximum zero crossing wave height (Hmax) method of data processing</dd><dt><span>conventions :</span></dt><dd>Copernicus Marine In Situ reference table 1</dd><dt><span>flag_values :</span></dt><dd>R, A, D</dd><dt><span>flag_meanings :</span></dt><dd>real-time adjusted-in-real-time delayed-mode</dd></dl></div><div class="xr-var-data"><pre>array([[b'R', nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [b'R', nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [b'R', nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]], dtype=object)</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>VTM02</span></div><div class="xr-var-dims">(TIME, DEPTH)</div><div class="xr-var-dtype">float64</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-34d70f8e-0310-414e-bc63-050be1e8975d" class="xr-var-attrs-in" type="checkbox"><label for="attrs-34d70f8e-0310-414e-bc63-050be1e8975d" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-a932f06c-5cc3-4afd-b8c3-04aa7e1ed568" class="xr-var-data-in" type="checkbox"><label for="data-a932f06c-5cc3-4afd-b8c3-04aa7e1ed568" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>standard_name :</span></dt><dd>sea_surface_wave_mean_period_from_variance_spectral_density_second_frequency_moment</dd><dt><span>units :</span></dt><dd>s</dd><dt><span>long_name :</span></dt><dd>Spectral moments (0,2) wave period (Tm02)</dd><dt><span>valid_min :</span></dt><dd>1000</dd><dt><span>valid_max :</span></dt><dd>25000</dd><dt><span>comment :</span></dt><dd> </dd><dt><span>uncertainty :</span></dt><dd> </dd><dt><span>accuracy :</span></dt><dd> </dd><dt><span>precision :</span></dt><dd> </dd><dt><span>resolution :</span></dt><dd> </dd><dt><span>cell_methods :</span></dt><dd> </dd><dt><span>type_of_analysis :</span></dt><dd>spectral analysis</dd><dt><span>sensor_depth :</span></dt><dd>0.0</dd><dt><span>sensor_mount :</span></dt><dd> </dd><dt><span>sensor_orientation :</span></dt><dd> </dd><dt><span>data_mode :</span></dt><dd>M</dd><dt><span>ancillary_variables :</span></dt><dd>VTM02_QC VTM02_DM</dd></dl></div><div class="xr-var-data"><pre>array([[  nan,   nan,   nan, ...,   nan,   nan,   nan],
       [4.   ,   nan,   nan, ...,   nan,   nan,   nan],
       [  nan,   nan,   nan, ...,   nan,   nan,   nan],
       ...,
       [4.878,   nan,   nan, ...,   nan,   nan,   nan],
       [  nan,   nan,   nan, ...,   nan,   nan,   nan],
       [5.063,   nan,   nan, ...,   nan,   nan,   nan]])</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>VTM02_QC</span></div><div class="xr-var-dims">(TIME, DEPTH)</div><div class="xr-var-dtype">float32</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-39e6d3bd-fdd3-4280-9adb-bd87c04de8c7" class="xr-var-attrs-in" type="checkbox"><label for="attrs-39e6d3bd-fdd3-4280-9adb-bd87c04de8c7" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-9928f3ad-e29e-4d20-afaf-6789fbbf5f60" class="xr-var-data-in" type="checkbox"><label for="data-9928f3ad-e29e-4d20-afaf-6789fbbf5f60" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>Spectral moments (0,2) wave period (Tm02) quality flag</dd><dt><span>conventions :</span></dt><dd>Copernicus Marine In Situ reference table 2</dd><dt><span>valid_min :</span></dt><dd>0</dd><dt><span>valid_max :</span></dt><dd>9</dd><dt><span>flag_values :</span></dt><dd>[0 1 2 3 4 5 6 7 8 9]</dd><dt><span>flag_meanings :</span></dt><dd>no_qc_performed good_data probably_good_data bad_data_that_are_potentially_correctable bad_data value_changed value_below_detection nominal_value interpolated_value missing_value</dd></dl></div><div class="xr-var-data"><pre>array([[ 9., nan, nan, ..., nan, nan, nan],
       [ 1., nan, nan, ..., nan, nan, nan],
       [ 9., nan, nan, ..., nan, nan, nan],
       ...,
       [ 1., nan, nan, ..., nan, nan, nan],
       [ 9., nan, nan, ..., nan, nan, nan],
       [ 1., nan, nan, ..., nan, nan, nan]], dtype=float32)</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>VTM02_DM</span></div><div class="xr-var-dims">(TIME, DEPTH)</div><div class="xr-var-dtype">object</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-9e1002bc-bd87-4347-8e88-c2db0ee178b7" class="xr-var-attrs-in" type="checkbox"><label for="attrs-9e1002bc-bd87-4347-8e88-c2db0ee178b7" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-839f8451-9662-4640-b5b9-5294b42d8c17" class="xr-var-data-in" type="checkbox"><label for="data-839f8451-9662-4640-b5b9-5294b42d8c17" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>Spectral moments (0,2) wave period (Tm02) method of data processing</dd><dt><span>conventions :</span></dt><dd>Copernicus Marine In Situ reference table 1</dd><dt><span>flag_values :</span></dt><dd>R, A, D</dd><dt><span>flag_meanings :</span></dt><dd>real-time adjusted-in-real-time delayed-mode</dd></dl></div><div class="xr-var-data"><pre>array([[nan, nan, nan, ..., nan, nan, nan],
       [b'R', nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [b'R', nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [b'R', nan, nan, ..., nan, nan, nan]], dtype=object)</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>VTPK</span></div><div class="xr-var-dims">(TIME, DEPTH)</div><div class="xr-var-dtype">float64</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-f293b6dc-539e-470b-81de-e841459f73bb" class="xr-var-attrs-in" type="checkbox"><label for="attrs-f293b6dc-539e-470b-81de-e841459f73bb" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-292920fc-6034-4a25-b50a-643d2a436da6" class="xr-var-data-in" type="checkbox"><label for="data-292920fc-6034-4a25-b50a-643d2a436da6" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>standard_name :</span></dt><dd>sea_surface_wave_period_at_variance_spectral_density_maximum</dd><dt><span>units :</span></dt><dd>s</dd><dt><span>long_name :</span></dt><dd>Wave period at spectral peak / peak period (Tp)</dd><dt><span>valid_min :</span></dt><dd>1000</dd><dt><span>valid_max :</span></dt><dd>30000</dd><dt><span>comment :</span></dt><dd> </dd><dt><span>uncertainty :</span></dt><dd> </dd><dt><span>accuracy :</span></dt><dd> </dd><dt><span>precision :</span></dt><dd> </dd><dt><span>resolution :</span></dt><dd> </dd><dt><span>cell_methods :</span></dt><dd> </dd><dt><span>type_of_analysis :</span></dt><dd>spectral analysis</dd><dt><span>sensor_depth :</span></dt><dd>0.0</dd><dt><span>sensor_mount :</span></dt><dd> </dd><dt><span>sensor_orientation :</span></dt><dd> </dd><dt><span>data_mode :</span></dt><dd>M</dd><dt><span>ancillary_variables :</span></dt><dd>VTPK_QC VTPK_DM</dd></dl></div><div class="xr-var-data"><pre>array([[ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [5.  ,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       ...,
       [6.25,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [6.67,  nan,  nan, ...,  nan,  nan,  nan]])</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>VTPK_QC</span></div><div class="xr-var-dims">(TIME, DEPTH)</div><div class="xr-var-dtype">float32</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-43f8c498-7a6b-4374-8220-cf9e4210926a" class="xr-var-attrs-in" type="checkbox"><label for="attrs-43f8c498-7a6b-4374-8220-cf9e4210926a" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-a68fa30c-0023-4c51-885a-47961561830f" class="xr-var-data-in" type="checkbox"><label for="data-a68fa30c-0023-4c51-885a-47961561830f" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>Wave period at spectral peak / peak period (Tp) quality flag</dd><dt><span>conventions :</span></dt><dd>Copernicus Marine In Situ reference table 2</dd><dt><span>valid_min :</span></dt><dd>0</dd><dt><span>valid_max :</span></dt><dd>9</dd><dt><span>flag_values :</span></dt><dd>[0 1 2 3 4 5 6 7 8 9]</dd><dt><span>flag_meanings :</span></dt><dd>no_qc_performed good_data probably_good_data bad_data_that_are_potentially_correctable bad_data value_changed value_below_detection nominal_value interpolated_value missing_value</dd></dl></div><div class="xr-var-data"><pre>array([[ 9., nan, nan, ..., nan, nan, nan],
       [ 1., nan, nan, ..., nan, nan, nan],
       [ 9., nan, nan, ..., nan, nan, nan],
       ...,
       [ 1., nan, nan, ..., nan, nan, nan],
       [ 9., nan, nan, ..., nan, nan, nan],
       [ 1., nan, nan, ..., nan, nan, nan]], dtype=float32)</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>VTPK_DM</span></div><div class="xr-var-dims">(TIME, DEPTH)</div><div class="xr-var-dtype">object</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-85ced6b5-f23c-4f49-b1e0-89641e1bab57" class="xr-var-attrs-in" type="checkbox"><label for="attrs-85ced6b5-f23c-4f49-b1e0-89641e1bab57" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-8db3cfa7-5a56-481c-82c9-5999f51ae866" class="xr-var-data-in" type="checkbox"><label for="data-8db3cfa7-5a56-481c-82c9-5999f51ae866" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>Wave period at spectral peak / peak period (Tp) method of data processing</dd><dt><span>conventions :</span></dt><dd>Copernicus Marine In Situ reference table 1</dd><dt><span>flag_values :</span></dt><dd>R, A, D</dd><dt><span>flag_meanings :</span></dt><dd>real-time adjusted-in-real-time delayed-mode</dd></dl></div><div class="xr-var-data"><pre>array([[nan, nan, nan, ..., nan, nan, nan],
       [b'R', nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [b'R', nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [b'R', nan, nan, ..., nan, nan, nan]], dtype=object)</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>VTZA</span></div><div class="xr-var-dims">(TIME, DEPTH)</div><div class="xr-var-dtype">float64</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-d4fdb01b-2f3b-4bd9-a10f-0be30b05f1af" class="xr-var-attrs-in" type="checkbox"><label for="attrs-d4fdb01b-2f3b-4bd9-a10f-0be30b05f1af" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-d82dd646-4d88-409d-86dc-384f2a6b012f" class="xr-var-data-in" type="checkbox"><label for="data-d82dd646-4d88-409d-86dc-384f2a6b012f" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>standard_name :</span></dt><dd>sea_surface_wave_mean_period</dd><dt><span>units :</span></dt><dd>s</dd><dt><span>long_name :</span></dt><dd>Average zero crossing wave period (Tz)</dd><dt><span>valid_min :</span></dt><dd>2000</dd><dt><span>valid_max :</span></dt><dd>25000</dd><dt><span>comment :</span></dt><dd> </dd><dt><span>uncertainty :</span></dt><dd> </dd><dt><span>accuracy :</span></dt><dd> </dd><dt><span>precision :</span></dt><dd> </dd><dt><span>resolution :</span></dt><dd> </dd><dt><span>cell_methods :</span></dt><dd> </dd><dt><span>type_of_analysis :</span></dt><dd>zero crossing</dd><dt><span>sensor_depth :</span></dt><dd>0.0</dd><dt><span>sensor_mount :</span></dt><dd> </dd><dt><span>sensor_orientation :</span></dt><dd> </dd><dt><span>data_mode :</span></dt><dd>R</dd><dt><span>ancillary_variables :</span></dt><dd>VTZA_QC</dd></dl></div><div class="xr-var-data"><pre>array([[4.12,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [4.18,  nan,  nan, ...,  nan,  nan,  nan],
       ...,
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [5.44,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan]])</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>VTZA_QC</span></div><div class="xr-var-dims">(TIME, DEPTH)</div><div class="xr-var-dtype">float32</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-023d8381-653a-4e83-ac7b-80caa5e00528" class="xr-var-attrs-in" type="checkbox"><label for="attrs-023d8381-653a-4e83-ac7b-80caa5e00528" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-c9a68535-b071-4460-afec-a46b21d7e6d4" class="xr-var-data-in" type="checkbox"><label for="data-c9a68535-b071-4460-afec-a46b21d7e6d4" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>Average zero crossing wave period (Tz) quality flag</dd><dt><span>conventions :</span></dt><dd>Copernicus Marine In Situ reference table 2</dd><dt><span>valid_min :</span></dt><dd>0</dd><dt><span>valid_max :</span></dt><dd>9</dd><dt><span>flag_values :</span></dt><dd>[0 1 2 3 4 5 6 7 8 9]</dd><dt><span>flag_meanings :</span></dt><dd>no_qc_performed good_data probably_good_data bad_data_that_are_potentially_correctable bad_data value_changed value_below_detection nominal_value interpolated_value missing_value</dd></dl></div><div class="xr-var-data"><pre>array([[ 1., nan, nan, ..., nan, nan, nan],
       [ 9., nan, nan, ..., nan, nan, nan],
       [ 1., nan, nan, ..., nan, nan, nan],
       ...,
       [ 9., nan, nan, ..., nan, nan, nan],
       [ 1., nan, nan, ..., nan, nan, nan],
       [ 9., nan, nan, ..., nan, nan, nan]], dtype=float32)</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>VPED</span></div><div class="xr-var-dims">(TIME, DEPTH)</div><div class="xr-var-dtype">float64</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-95d80003-1660-4b99-bb3b-3c22098e5eef" class="xr-var-attrs-in" type="checkbox"><label for="attrs-95d80003-1660-4b99-bb3b-3c22098e5eef" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-394dc60b-c61d-4914-a5ab-92058defd55f" class="xr-var-data-in" type="checkbox"><label for="data-394dc60b-c61d-4914-a5ab-92058defd55f" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>standard_name :</span></dt><dd>sea_surface_wave_from_direction_at_variance_spectral_density_maximum</dd><dt><span>units :</span></dt><dd>degree</dd><dt><span>long_name :</span></dt><dd>Wave principal direction at spectral peak</dd><dt><span>valid_min :</span></dt><dd>0</dd><dt><span>valid_max :</span></dt><dd>360000</dd><dt><span>comment :</span></dt><dd> </dd><dt><span>uncertainty :</span></dt><dd> </dd><dt><span>accuracy :</span></dt><dd> </dd><dt><span>precision :</span></dt><dd> </dd><dt><span>resolution :</span></dt><dd> </dd><dt><span>cell_methods :</span></dt><dd> </dd><dt><span>type_of_analysis :</span></dt><dd>spectral analysis</dd><dt><span>sensor_depth :</span></dt><dd>0.0</dd><dt><span>sensor_mount :</span></dt><dd> </dd><dt><span>sensor_orientation :</span></dt><dd> </dd><dt><span>data_mode :</span></dt><dd>M</dd><dt><span>ancillary_variables :</span></dt><dd>VPED_QC VPED_DM</dd></dl></div><div class="xr-var-data"><pre>array([[       nan,        nan,        nan, ...,        nan,        nan,
               nan],
       [  2.8     ,        nan,        nan, ...,        nan,        nan,
               nan],
       [       nan,        nan,        nan, ...,        nan,        nan,
               nan],
       ...,
       [234.800011,        nan,        nan, ...,        nan,        nan,
               nan],
       [       nan,        nan,        nan, ...,        nan,        nan,
               nan],
       [244.700012,        nan,        nan, ...,        nan,        nan,
               nan]])</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>VPED_QC</span></div><div class="xr-var-dims">(TIME, DEPTH)</div><div class="xr-var-dtype">float32</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-66391810-08a1-4dc9-a700-3182a54751ee" class="xr-var-attrs-in" type="checkbox"><label for="attrs-66391810-08a1-4dc9-a700-3182a54751ee" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-8ec429b6-749e-4053-8671-0e66e4f8f5eb" class="xr-var-data-in" type="checkbox"><label for="data-8ec429b6-749e-4053-8671-0e66e4f8f5eb" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>Wave principal direction at spectral peak quality flag</dd><dt><span>conventions :</span></dt><dd>Copernicus Marine In Situ reference table 2</dd><dt><span>valid_min :</span></dt><dd>0</dd><dt><span>valid_max :</span></dt><dd>9</dd><dt><span>flag_values :</span></dt><dd>[0 1 2 3 4 5 6 7 8 9]</dd><dt><span>flag_meanings :</span></dt><dd>no_qc_performed good_data probably_good_data bad_data_that_are_potentially_correctable bad_data value_changed value_below_detection nominal_value interpolated_value missing_value</dd></dl></div><div class="xr-var-data"><pre>array([[ 9., nan, nan, ..., nan, nan, nan],
       [ 1., nan, nan, ..., nan, nan, nan],
       [ 9., nan, nan, ..., nan, nan, nan],
       ...,
       [ 1., nan, nan, ..., nan, nan, nan],
       [ 9., nan, nan, ..., nan, nan, nan],
       [ 1., nan, nan, ..., nan, nan, nan]], dtype=float32)</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>VPED_DM</span></div><div class="xr-var-dims">(TIME, DEPTH)</div><div class="xr-var-dtype">object</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-b3245f78-2951-47ba-8886-e53e8c49e8b0" class="xr-var-attrs-in" type="checkbox"><label for="attrs-b3245f78-2951-47ba-8886-e53e8c49e8b0" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-9ca96b17-12ae-49b7-a677-337eb5805825" class="xr-var-data-in" type="checkbox"><label for="data-9ca96b17-12ae-49b7-a677-337eb5805825" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>Wave principal direction at spectral peak method of data processing</dd><dt><span>conventions :</span></dt><dd>Copernicus Marine In Situ reference table 1</dd><dt><span>flag_values :</span></dt><dd>R, A, D</dd><dt><span>flag_meanings :</span></dt><dd>real-time adjusted-in-real-time delayed-mode</dd></dl></div><div class="xr-var-data"><pre>array([[nan, nan, nan, ..., nan, nan, nan],
       [b'R', nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [b'R', nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [b'R', nan, nan, ..., nan, nan, nan]], dtype=object)</pre></div></li></ul></div></li><li class="xr-section-item"><input id="section-3395bcee-9e15-4657-8d99-b9134925744c" class="xr-section-summary-in" type="checkbox"><label for="section-3395bcee-9e15-4657-8d99-b9134925744c" class="xr-section-summary">Attributes: <span>(46)</span></label><div class="xr-section-inline-details"></div><div class="xr-section-details"><dl class="xr-attrs"><dt><span>platform_code :</span></dt><dd>FINO1</dd><dt><span>platform_name :</span></dt><dd></dd><dt><span>data_mode :</span></dt><dd>M</dd><dt><span>title :</span></dt><dd>NWS - NRT in situ Observations</dd><dt><span>summary :</span></dt><dd>Oceanographic data from North West Shelf</dd><dt><span>naming_authority :</span></dt><dd>Copernicus Marine In Situ</dd><dt><span>id :</span></dt><dd>NO_TS_MO_FINO1_202209</dd><dt><span>wmo_platform_code :</span></dt><dd>6201065</dd><dt><span>ices_platform_code :</span></dt><dd></dd><dt><span>source :</span></dt><dd>mooring</dd><dt><span>source_platform_category_code :</span></dt><dd>48</dd><dt><span>institution_edmo_code :</span></dt><dd>3356</dd><dt><span>institution :</span></dt><dd>R and D centre Kiel University of Applied Sciences</dd><dt><span>institution_references :</span></dt><dd>www.fh-kiel-gmbh.de/en/</dd><dt><span>site_code :</span></dt><dd></dd><dt><span>comment :</span></dt><dd></dd><dt><span>contact :</span></dt><dd>cmems-service@bsh.de</dd><dt><span>area :</span></dt><dd>North Atlantic Ocean</dd><dt><span>geospatial_lat_min :</span></dt><dd>54.00000</dd><dt><span>geospatial_lat_max :</span></dt><dd>54.00000</dd><dt><span>geospatial_lon_min :</span></dt><dd>6.58333</dd><dt><span>geospatial_lon_max :</span></dt><dd>6.58333</dd><dt><span>last_date_observation :</span></dt><dd>2022-09-30T23:32:00Z</dd><dt><span>last_latitude_observation :</span></dt><dd>54.00000</dd><dt><span>last_longitude_observation :</span></dt><dd>6.58333</dd><dt><span>geospatial_vertical_min :</span></dt><dd>0.00000</dd><dt><span>geospatial_vertical_max :</span></dt><dd>25.00000</dd><dt><span>time_coverage_start :</span></dt><dd>2022-09-01T00:00:00Z</dd><dt><span>time_coverage_end :</span></dt><dd>2022-09-30T23:32:00Z</dd><dt><span>cdm_data_type :</span></dt><dd>timeSeries</dd><dt><span>data_type :</span></dt><dd>OceanSITES time-series data</dd><dt><span>bottom_depth :</span></dt><dd></dd><dt><span>format_version :</span></dt><dd>1.4</dd><dt><span>Conventions :</span></dt><dd>CF-1.6 Copernicus-InSituTAC-FormatManual-1.42 Copernicus-InSituTAC-SRD-1.5 Copernicus-InSituTAC-ParametersList-3.2.1</dd><dt><span>netcdf_version :</span></dt><dd>netCDF-4 classic model</dd><dt><span>references :</span></dt><dd>http://marine.copernicus.eu http://www.marineinsitu.eu</dd><dt><span>data_assembly_center :</span></dt><dd>BSH</dd><dt><span>update_interval :</span></dt><dd>PT1H</dd><dt><span>citation :</span></dt><dd>These data were collected and made freely available by the Copernicus project and the programs that contribute to it</dd><dt><span>distribution_statement :</span></dt><dd>These data follow Copernicus standards; they are public and free of charge. User assumes all risk for use of data. User must display citation in any publication or product using data. User must contact PI prior to any commercial use of data.</dd><dt><span>doi :</span></dt><dd></dd><dt><span>pi_name :</span></dt><dd></dd><dt><span>qc_manual :</span></dt><dd>OceanSITES User's Manual v1.2</dd><dt><span>date_update :</span></dt><dd>2022-10-07T05:39:40Z</dd><dt><span>history :</span></dt><dd>2022-10-01T18:04:25Z : Creation; 2022-10-07T05:39:40Z, BSH North West Shelf PU: Monthly subset 202209 extracted from history file NO_TS_MO_FINO1.nc</dd><dt><span>wmo_inst_type :</span></dt><dd></dd></dl></div></li></ul></div></div>
</div>
</div>
<p>CMEMS <em>in-situ</em> data is provided in a standardised format, the <a href="http://www.oceansites.org/docs/oceansites_data_format_reference_manual.pdf">OceanSITES time-series data format</a>.</p>
<blockquote class="blockquote">
<p>“<em>The OceanSITES programme is the global network of open-ocean sustained time series sites, called ocean reference stations, being implemented by an international partnership of researchers and agencies. OceanSITES provides fixed-point time series of various physical, biogeochemical, ecosystem and atmospheric variables at locations around the globe, from the atmosphere and sea surface to the seafloor. The program’s objective is to build and maintain a multidisciplinary global network for a broad range of research and operational applications including climate, carbon, and ecosystem variability and forecasting and ocean state validation</em>”</p>
</blockquote>
<p>Find out which variables we are interested in to extract:</p>
<div class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>pd.DataFrame([{<span class="st">'name'</span>: fino[var].name, <span class="st">'standard_name'</span>: fino[var].standard_name, <span class="st">'units'</span>: fino[var].units} <span class="cf">for</span> var <span class="kw">in</span> fino.data_vars <span class="cf">if</span> <span class="bu">hasattr</span>(fino[var],<span class="st">"units"</span>)])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="25">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>name</th>
      <th>standard_name</th>
      <th>units</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>TEMP</td>
      <td>sea_water_temperature</td>
      <td>degrees_C</td>
    </tr>
    <tr>
      <th>1</th>
      <td>VHM0</td>
      <td>sea_surface_wave_significant_height</td>
      <td>m</td>
    </tr>
    <tr>
      <th>2</th>
      <td>VZMX</td>
      <td>sea_surface_wave_maximum_height</td>
      <td>m</td>
    </tr>
    <tr>
      <th>3</th>
      <td>VTM02</td>
      <td>sea_surface_wave_mean_period_from_variance_spe...</td>
      <td>s</td>
    </tr>
    <tr>
      <th>4</th>
      <td>VTPK</td>
      <td>sea_surface_wave_period_at_variance_spectral_d...</td>
      <td>s</td>
    </tr>
    <tr>
      <th>5</th>
      <td>VTZA</td>
      <td>sea_surface_wave_mean_period</td>
      <td>s</td>
    </tr>
    <tr>
      <th>6</th>
      <td>VPED</td>
      <td>sea_surface_wave_from_direction_at_variance_sp...</td>
      <td>degree</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<p>The data have a DEPTH dimension, even though variables are only measured at a single level and doesn’t vary in time although the format allows for it.</p>
<p>I.e. temperature (TEMP) is available at level 1 (0.5 m)</p>
<div class="cell" data-execution_count="61">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>fino.DEPH.plot.line(x<span class="op">=</span><span class="st">'TIME'</span>)<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="Dfs0_-_CMEMS_insitu_files/figure-html/cell-5-output-1.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-execution_count="49">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>fino[<span class="st">'TEMP'</span>].plot.line(<span class="st">"-^"</span>,x<span class="op">=</span><span class="st">'TIME'</span>)<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="Dfs0_-_CMEMS_insitu_files/figure-html/cell-6-output-1.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-execution_count="48">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>fino[<span class="st">'VHM0'</span>].plot.line(<span class="st">"-^"</span>,x<span class="op">=</span><span class="st">'TIME'</span>)<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="Dfs0_-_CMEMS_insitu_files/figure-html/cell-7-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>Wave data are only available at the surface.</p>
<div class="cell" data-execution_count="63">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>fino[[<span class="st">'VHM0'</span>,<span class="st">'VTZA'</span>,<span class="st">'VPED'</span>]].isel(DEPTH<span class="op">=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="63">

<div><svg style="position: absolute; width: 0; height: 0; overflow: hidden">
<defs>
<symbol id="icon-database" viewbox="0 0 32 32">
<path d="M16 0c-8.837 0-16 2.239-16 5v4c0 2.761 7.163 5 16 5s16-2.239 16-5v-4c0-2.761-7.163-5-16-5z"></path>
<path d="M16 17c-8.837 0-16-2.239-16-5v6c0 2.761 7.163 5 16 5s16-2.239 16-5v-6c0 2.761-7.163 5-16 5z"></path>
<path d="M16 26c-8.837 0-16-2.239-16-5v6c0 2.761 7.163 5 16 5s16-2.239 16-5v-6c0 2.761-7.163 5-16 5z"></path>
</symbol>
<symbol id="icon-file-text2" viewbox="0 0 32 32">
<path d="M28.681 7.159c-0.694-0.947-1.662-2.053-2.724-3.116s-2.169-2.030-3.116-2.724c-1.612-1.182-2.393-1.319-2.841-1.319h-15.5c-1.378 0-2.5 1.121-2.5 2.5v27c0 1.378 1.122 2.5 2.5 2.5h23c1.378 0 2.5-1.122 2.5-2.5v-19.5c0-0.448-0.137-1.23-1.319-2.841zM24.543 5.457c0.959 0.959 1.712 1.825 2.268 2.543h-4.811v-4.811c0.718 0.556 1.584 1.309 2.543 2.268zM28 29.5c0 0.271-0.229 0.5-0.5 0.5h-23c-0.271 0-0.5-0.229-0.5-0.5v-27c0-0.271 0.229-0.5 0.5-0.5 0 0 15.499-0 15.5 0v7c0 0.552 0.448 1 1 1h7v19.5z"></path>
<path d="M23 26h-14c-0.552 0-1-0.448-1-1s0.448-1 1-1h14c0.552 0 1 0.448 1 1s-0.448 1-1 1z"></path>
<path d="M23 22h-14c-0.552 0-1-0.448-1-1s0.448-1 1-1h14c0.552 0 1 0.448 1 1s-0.448 1-1 1z"></path>
<path d="M23 18h-14c-0.552 0-1-0.448-1-1s0.448-1 1-1h14c0.552 0 1 0.448 1 1s-0.448 1-1 1z"></path>
</symbol>
</defs>
</svg>
<style>/* CSS stylesheet for displaying xarray objects in jupyterlab.
 *
 */

:root {
  --xr-font-color0: var(--jp-content-font-color0, rgba(0, 0, 0, 1));
  --xr-font-color2: var(--jp-content-font-color2, rgba(0, 0, 0, 0.54));
  --xr-font-color3: var(--jp-content-font-color3, rgba(0, 0, 0, 0.38));
  --xr-border-color: var(--jp-border-color2, #e0e0e0);
  --xr-disabled-color: var(--jp-layout-color3, #bdbdbd);
  --xr-background-color: var(--jp-layout-color0, white);
  --xr-background-color-row-even: var(--jp-layout-color1, white);
  --xr-background-color-row-odd: var(--jp-layout-color2, #eeeeee);
}

html[theme=dark],
body[data-theme=dark],
body.vscode-dark {
  --xr-font-color0: rgba(255, 255, 255, 1);
  --xr-font-color2: rgba(255, 255, 255, 0.54);
  --xr-font-color3: rgba(255, 255, 255, 0.38);
  --xr-border-color: #1F1F1F;
  --xr-disabled-color: #515151;
  --xr-background-color: #111111;
  --xr-background-color-row-even: #111111;
  --xr-background-color-row-odd: #313131;
}

.xr-wrap {
  display: block !important;
  min-width: 300px;
  max-width: 700px;
}

.xr-text-repr-fallback {
  /* fallback to plain text repr when CSS is not injected (untrusted notebook) */
  display: none;
}

.xr-header {
  padding-top: 6px;
  padding-bottom: 6px;
  margin-bottom: 4px;
  border-bottom: solid 1px var(--xr-border-color);
}

.xr-header > div,
.xr-header > ul {
  display: inline;
  margin-top: 0;
  margin-bottom: 0;
}

.xr-obj-type,
.xr-array-name {
  margin-left: 2px;
  margin-right: 10px;
}

.xr-obj-type {
  color: var(--xr-font-color2);
}

.xr-sections {
  padding-left: 0 !important;
  display: grid;
  grid-template-columns: 150px auto auto 1fr 20px 20px;
}

.xr-section-item {
  display: contents;
}

.xr-section-item input {
  display: none;
}

.xr-section-item input + label {
  color: var(--xr-disabled-color);
}

.xr-section-item input:enabled + label {
  cursor: pointer;
  color: var(--xr-font-color2);
}

.xr-section-item input:enabled + label:hover {
  color: var(--xr-font-color0);
}

.xr-section-summary {
  grid-column: 1;
  color: var(--xr-font-color2);
  font-weight: 500;
}

.xr-section-summary > span {
  display: inline-block;
  padding-left: 0.5em;
}

.xr-section-summary-in:disabled + label {
  color: var(--xr-font-color2);
}

.xr-section-summary-in + label:before {
  display: inline-block;
  content: '►';
  font-size: 11px;
  width: 15px;
  text-align: center;
}

.xr-section-summary-in:disabled + label:before {
  color: var(--xr-disabled-color);
}

.xr-section-summary-in:checked + label:before {
  content: '▼';
}

.xr-section-summary-in:checked + label > span {
  display: none;
}

.xr-section-summary,
.xr-section-inline-details {
  padding-top: 4px;
  padding-bottom: 4px;
}

.xr-section-inline-details {
  grid-column: 2 / -1;
}

.xr-section-details {
  display: none;
  grid-column: 1 / -1;
  margin-bottom: 5px;
}

.xr-section-summary-in:checked ~ .xr-section-details {
  display: contents;
}

.xr-array-wrap {
  grid-column: 1 / -1;
  display: grid;
  grid-template-columns: 20px auto;
}

.xr-array-wrap > label {
  grid-column: 1;
  vertical-align: top;
}

.xr-preview {
  color: var(--xr-font-color3);
}

.xr-array-preview,
.xr-array-data {
  padding: 0 5px !important;
  grid-column: 2;
}

.xr-array-data,
.xr-array-in:checked ~ .xr-array-preview {
  display: none;
}

.xr-array-in:checked ~ .xr-array-data,
.xr-array-preview {
  display: inline-block;
}

.xr-dim-list {
  display: inline-block !important;
  list-style: none;
  padding: 0 !important;
  margin: 0;
}

.xr-dim-list li {
  display: inline-block;
  padding: 0;
  margin: 0;
}

.xr-dim-list:before {
  content: '(';
}

.xr-dim-list:after {
  content: ')';
}

.xr-dim-list li:not(:last-child):after {
  content: ',';
  padding-right: 5px;
}

.xr-has-index {
  font-weight: bold;
}

.xr-var-list,
.xr-var-item {
  display: contents;
}

.xr-var-item > div,
.xr-var-item label,
.xr-var-item > .xr-var-name span {
  background-color: var(--xr-background-color-row-even);
  margin-bottom: 0;
}

.xr-var-item > .xr-var-name:hover span {
  padding-right: 5px;
}

.xr-var-list > li:nth-child(odd) > div,
.xr-var-list > li:nth-child(odd) > label,
.xr-var-list > li:nth-child(odd) > .xr-var-name span {
  background-color: var(--xr-background-color-row-odd);
}

.xr-var-name {
  grid-column: 1;
}

.xr-var-dims {
  grid-column: 2;
}

.xr-var-dtype {
  grid-column: 3;
  text-align: right;
  color: var(--xr-font-color2);
}

.xr-var-preview {
  grid-column: 4;
}

.xr-var-name,
.xr-var-dims,
.xr-var-dtype,
.xr-preview,
.xr-attrs dt {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  padding-right: 10px;
}

.xr-var-name:hover,
.xr-var-dims:hover,
.xr-var-dtype:hover,
.xr-attrs dt:hover {
  overflow: visible;
  width: auto;
  z-index: 1;
}

.xr-var-attrs,
.xr-var-data {
  display: none;
  background-color: var(--xr-background-color) !important;
  padding-bottom: 5px !important;
}

.xr-var-attrs-in:checked ~ .xr-var-attrs,
.xr-var-data-in:checked ~ .xr-var-data {
  display: block;
}

.xr-var-data > table {
  float: right;
}

.xr-var-name span,
.xr-var-data,
.xr-attrs {
  padding-left: 25px !important;
}

.xr-attrs,
.xr-var-attrs,
.xr-var-data {
  grid-column: 1 / -1;
}

dl.xr-attrs {
  padding: 0;
  margin: 0;
  display: grid;
  grid-template-columns: 125px auto;
}

.xr-attrs dt,
.xr-attrs dd {
  padding: 0;
  margin: 0;
  float: left;
  padding-right: 10px;
  width: auto;
}

.xr-attrs dt {
  font-weight: normal;
  grid-column: 1;
}

.xr-attrs dt:hover span {
  display: inline-block;
  background: var(--xr-background-color);
  padding-right: 10px;
}

.xr-attrs dd {
  grid-column: 2;
  white-space: pre-wrap;
  word-break: break-all;
}

.xr-icon-database,
.xr-icon-file-text2 {
  display: inline-block;
  vertical-align: middle;
  width: 1em;
  height: 1.5em !important;
  stroke-width: 0;
  stroke: currentColor;
  fill: currentColor;
}
</style><pre class="xr-text-repr-fallback">&lt;xarray.Dataset&gt;
Dimensions:  (TIME: 2879)
Coordinates:
  * TIME     (TIME) datetime64[ns] 2022-09-01 ... 2022-09-30T23:31:59.999999744
    DEPH     (TIME) float32 0.0 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0 0.0 0.0
Data variables:
    VHM0     (TIME) float64 nan 1.11 nan 1.09 nan ... 2.46 nan 2.41 nan 2.51
    VTZA     (TIME) float64 4.12 nan 4.18 nan 4.0 nan ... nan 5.2 nan 5.44 nan
    VPED     (TIME) float64 nan 2.8 nan 353.0 nan ... 192.7 nan 234.8 nan 244.7
Attributes: (12/46)
    platform_code:                  FINO1
    platform_name:                  
    data_mode:                      M
    title:                          NWS - NRT in situ Observations
    summary:                        Oceanographic data from North West Shelf
    naming_authority:               Copernicus Marine In Situ
    ...                             ...
    doi:                            
    pi_name:                        
    qc_manual:                      OceanSITES User's Manual v1.2
    date_update:                    2022-10-07T05:39:40Z
    history:                        2022-10-01T18:04:25Z : Creation; 2022-10-...
    wmo_inst_type:                  </pre><div class="xr-wrap" style="display:none"><div class="xr-header"><div class="xr-obj-type">xarray.Dataset</div></div><ul class="xr-sections"><li class="xr-section-item"><input id="section-c7d9df75-c465-4cc8-90c4-1527c2c38e94" class="xr-section-summary-in" type="checkbox" disabled=""><label for="section-c7d9df75-c465-4cc8-90c4-1527c2c38e94" class="xr-section-summary" title="Expand/collapse section">Dimensions:</label><div class="xr-section-inline-details"><ul class="xr-dim-list"><li><span class="xr-has-index">TIME</span>: 2879</li></ul></div><div class="xr-section-details"></div></li><li class="xr-section-item"><input id="section-c1bf8423-1fab-4bc8-b0ee-f0737553d728" class="xr-section-summary-in" type="checkbox" checked=""><label for="section-c1bf8423-1fab-4bc8-b0ee-f0737553d728" class="xr-section-summary">Coordinates: <span>(2)</span></label><div class="xr-section-inline-details"></div><div class="xr-section-details"><ul class="xr-var-list"><li class="xr-var-item"><div class="xr-var-name"><span class="xr-has-index">TIME</span></div><div class="xr-var-dims">(TIME)</div><div class="xr-var-dtype">datetime64[ns]</div><div class="xr-var-preview xr-preview">2022-09-01 ... 2022-09-30T23:31:...</div><input id="attrs-faf1cf91-b6ed-4aa7-abed-68233ac92a34" class="xr-var-attrs-in" type="checkbox"><label for="attrs-faf1cf91-b6ed-4aa7-abed-68233ac92a34" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-e2aef9a5-a02f-493e-bbca-1130e4aa4833" class="xr-var-data-in" type="checkbox"><label for="data-e2aef9a5-a02f-493e-bbca-1130e4aa4833" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>Time</dd><dt><span>standard_name :</span></dt><dd>time</dd><dt><span>valid_min :</span></dt><dd>-90000.0</dd><dt><span>valid_max :</span></dt><dd>90000.0</dd><dt><span>uncertainty :</span></dt><dd> </dd><dt><span>comment :</span></dt><dd> </dd><dt><span>axis :</span></dt><dd>T</dd><dt><span>ancillary_variables :</span></dt><dd>TIME_QC</dd></dl></div><div class="xr-var-data"><pre>array(['2022-09-01T00:00:00.000000000', '2022-09-01T00:02:00.000000000',
       '2022-09-01T00:30:00.000000000', ..., '2022-09-30T23:02:00.000000000',
       '2022-09-30T23:30:00.000000000', '2022-09-30T23:31:59.999999744'],
      dtype='datetime64[ns]')</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>DEPH</span></div><div class="xr-var-dims">(TIME)</div><div class="xr-var-dtype">float32</div><div class="xr-var-preview xr-preview">0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0</div><input id="attrs-16881165-9d4d-4522-be24-a6a0e7c15101" class="xr-var-attrs-in" type="checkbox"><label for="attrs-16881165-9d4d-4522-be24-a6a0e7c15101" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-05b64380-6e9d-4b1d-a968-2a3422be7c0e" class="xr-var-data-in" type="checkbox"><label for="data-05b64380-6e9d-4b1d-a968-2a3422be7c0e" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>long_name :</span></dt><dd>Depth</dd><dt><span>standard_name :</span></dt><dd>depth</dd><dt><span>units :</span></dt><dd>m</dd><dt><span>positive :</span></dt><dd>down</dd><dt><span>valid_min :</span></dt><dd>-12000.0</dd><dt><span>valid_max :</span></dt><dd>12000.0</dd><dt><span>uncertainty :</span></dt><dd></dd><dt><span>comment :</span></dt><dd></dd><dt><span>axis :</span></dt><dd>Z</dd><dt><span>reference :</span></dt><dd>sea_level</dd><dt><span>data_mode :</span></dt><dd>R</dd><dt><span>ancillary_variables :</span></dt><dd>DEPH_QC</dd></dl></div><div class="xr-var-data"><pre>array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)</pre></div></li></ul></div></li><li class="xr-section-item"><input id="section-581034f4-a145-4171-ab76-d95dd3346a63" class="xr-section-summary-in" type="checkbox" checked=""><label for="section-581034f4-a145-4171-ab76-d95dd3346a63" class="xr-section-summary">Data variables: <span>(3)</span></label><div class="xr-section-inline-details"></div><div class="xr-section-details"><ul class="xr-var-list"><li class="xr-var-item"><div class="xr-var-name"><span>VHM0</span></div><div class="xr-var-dims">(TIME)</div><div class="xr-var-dtype">float64</div><div class="xr-var-preview xr-preview">nan 1.11 nan 1.09 ... 2.41 nan 2.51</div><input id="attrs-750e3641-53bf-4342-94ff-5459cd44d035" class="xr-var-attrs-in" type="checkbox"><label for="attrs-750e3641-53bf-4342-94ff-5459cd44d035" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-0aa8922b-da9e-4004-a14d-51bfd5d08028" class="xr-var-data-in" type="checkbox"><label for="data-0aa8922b-da9e-4004-a14d-51bfd5d08028" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>standard_name :</span></dt><dd>sea_surface_wave_significant_height</dd><dt><span>units :</span></dt><dd>m</dd><dt><span>long_name :</span></dt><dd>Spectral significant wave height (Hm0)</dd><dt><span>valid_min :</span></dt><dd>1</dd><dt><span>valid_max :</span></dt><dd>25000</dd><dt><span>comment :</span></dt><dd> </dd><dt><span>uncertainty :</span></dt><dd> </dd><dt><span>accuracy :</span></dt><dd> </dd><dt><span>precision :</span></dt><dd> </dd><dt><span>resolution :</span></dt><dd> </dd><dt><span>cell_methods :</span></dt><dd> </dd><dt><span>type_of_analysis :</span></dt><dd>spectral analysis</dd><dt><span>sensor_depth :</span></dt><dd>0.0</dd><dt><span>sensor_mount :</span></dt><dd> </dd><dt><span>sensor_orientation :</span></dt><dd> </dd><dt><span>data_mode :</span></dt><dd>M</dd><dt><span>ancillary_variables :</span></dt><dd>VHM0_QC VHM0_DM</dd></dl></div><div class="xr-var-data"><pre>array([ nan, 1.11,  nan, ..., 2.41,  nan, 2.51])</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>VTZA</span></div><div class="xr-var-dims">(TIME)</div><div class="xr-var-dtype">float64</div><div class="xr-var-preview xr-preview">4.12 nan 4.18 nan ... nan 5.44 nan</div><input id="attrs-a2074c62-a764-4a96-b1b6-2a24e9394937" class="xr-var-attrs-in" type="checkbox"><label for="attrs-a2074c62-a764-4a96-b1b6-2a24e9394937" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-e08bc89f-c00c-43b2-af1c-8d9665a6cda8" class="xr-var-data-in" type="checkbox"><label for="data-e08bc89f-c00c-43b2-af1c-8d9665a6cda8" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>standard_name :</span></dt><dd>sea_surface_wave_mean_period</dd><dt><span>units :</span></dt><dd>s</dd><dt><span>long_name :</span></dt><dd>Average zero crossing wave period (Tz)</dd><dt><span>valid_min :</span></dt><dd>2000</dd><dt><span>valid_max :</span></dt><dd>25000</dd><dt><span>comment :</span></dt><dd> </dd><dt><span>uncertainty :</span></dt><dd> </dd><dt><span>accuracy :</span></dt><dd> </dd><dt><span>precision :</span></dt><dd> </dd><dt><span>resolution :</span></dt><dd> </dd><dt><span>cell_methods :</span></dt><dd> </dd><dt><span>type_of_analysis :</span></dt><dd>zero crossing</dd><dt><span>sensor_depth :</span></dt><dd>0.0</dd><dt><span>sensor_mount :</span></dt><dd> </dd><dt><span>sensor_orientation :</span></dt><dd> </dd><dt><span>data_mode :</span></dt><dd>R</dd><dt><span>ancillary_variables :</span></dt><dd>VTZA_QC</dd></dl></div><div class="xr-var-data"><pre>array([4.12,  nan, 4.18, ...,  nan, 5.44,  nan])</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>VPED</span></div><div class="xr-var-dims">(TIME)</div><div class="xr-var-dtype">float64</div><div class="xr-var-preview xr-preview">nan 2.8 nan ... 234.8 nan 244.7</div><input id="attrs-ad8b1cca-e016-475d-bafb-ea6cd167135b" class="xr-var-attrs-in" type="checkbox"><label for="attrs-ad8b1cca-e016-475d-bafb-ea6cd167135b" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-0af7e28a-fbf4-4962-96bc-2fa07f2f5ea0" class="xr-var-data-in" type="checkbox"><label for="data-0af7e28a-fbf4-4962-96bc-2fa07f2f5ea0" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>standard_name :</span></dt><dd>sea_surface_wave_from_direction_at_variance_spectral_density_maximum</dd><dt><span>units :</span></dt><dd>degree</dd><dt><span>long_name :</span></dt><dd>Wave principal direction at spectral peak</dd><dt><span>valid_min :</span></dt><dd>0</dd><dt><span>valid_max :</span></dt><dd>360000</dd><dt><span>comment :</span></dt><dd> </dd><dt><span>uncertainty :</span></dt><dd> </dd><dt><span>accuracy :</span></dt><dd> </dd><dt><span>precision :</span></dt><dd> </dd><dt><span>resolution :</span></dt><dd> </dd><dt><span>cell_methods :</span></dt><dd> </dd><dt><span>type_of_analysis :</span></dt><dd>spectral analysis</dd><dt><span>sensor_depth :</span></dt><dd>0.0</dd><dt><span>sensor_mount :</span></dt><dd> </dd><dt><span>sensor_orientation :</span></dt><dd> </dd><dt><span>data_mode :</span></dt><dd>M</dd><dt><span>ancillary_variables :</span></dt><dd>VPED_QC VPED_DM</dd></dl></div><div class="xr-var-data"><pre>array([       nan,   2.8     ,        nan, ..., 234.800011,        nan,
       244.700012])</pre></div></li></ul></div></li><li class="xr-section-item"><input id="section-94329b8f-2137-4e23-86d9-39534ac0cedb" class="xr-section-summary-in" type="checkbox"><label for="section-94329b8f-2137-4e23-86d9-39534ac0cedb" class="xr-section-summary">Attributes: <span>(46)</span></label><div class="xr-section-inline-details"></div><div class="xr-section-details"><dl class="xr-attrs"><dt><span>platform_code :</span></dt><dd>FINO1</dd><dt><span>platform_name :</span></dt><dd></dd><dt><span>data_mode :</span></dt><dd>M</dd><dt><span>title :</span></dt><dd>NWS - NRT in situ Observations</dd><dt><span>summary :</span></dt><dd>Oceanographic data from North West Shelf</dd><dt><span>naming_authority :</span></dt><dd>Copernicus Marine In Situ</dd><dt><span>id :</span></dt><dd>NO_TS_MO_FINO1_202209</dd><dt><span>wmo_platform_code :</span></dt><dd>6201065</dd><dt><span>ices_platform_code :</span></dt><dd></dd><dt><span>source :</span></dt><dd>mooring</dd><dt><span>source_platform_category_code :</span></dt><dd>48</dd><dt><span>institution_edmo_code :</span></dt><dd>3356</dd><dt><span>institution :</span></dt><dd>R and D centre Kiel University of Applied Sciences</dd><dt><span>institution_references :</span></dt><dd>www.fh-kiel-gmbh.de/en/</dd><dt><span>site_code :</span></dt><dd></dd><dt><span>comment :</span></dt><dd></dd><dt><span>contact :</span></dt><dd>cmems-service@bsh.de</dd><dt><span>area :</span></dt><dd>North Atlantic Ocean</dd><dt><span>geospatial_lat_min :</span></dt><dd>54.00000</dd><dt><span>geospatial_lat_max :</span></dt><dd>54.00000</dd><dt><span>geospatial_lon_min :</span></dt><dd>6.58333</dd><dt><span>geospatial_lon_max :</span></dt><dd>6.58333</dd><dt><span>last_date_observation :</span></dt><dd>2022-09-30T23:32:00Z</dd><dt><span>last_latitude_observation :</span></dt><dd>54.00000</dd><dt><span>last_longitude_observation :</span></dt><dd>6.58333</dd><dt><span>geospatial_vertical_min :</span></dt><dd>0.00000</dd><dt><span>geospatial_vertical_max :</span></dt><dd>25.00000</dd><dt><span>time_coverage_start :</span></dt><dd>2022-09-01T00:00:00Z</dd><dt><span>time_coverage_end :</span></dt><dd>2022-09-30T23:32:00Z</dd><dt><span>cdm_data_type :</span></dt><dd>timeSeries</dd><dt><span>data_type :</span></dt><dd>OceanSITES time-series data</dd><dt><span>bottom_depth :</span></dt><dd></dd><dt><span>format_version :</span></dt><dd>1.4</dd><dt><span>Conventions :</span></dt><dd>CF-1.6 Copernicus-InSituTAC-FormatManual-1.42 Copernicus-InSituTAC-SRD-1.5 Copernicus-InSituTAC-ParametersList-3.2.1</dd><dt><span>netcdf_version :</span></dt><dd>netCDF-4 classic model</dd><dt><span>references :</span></dt><dd>http://marine.copernicus.eu http://www.marineinsitu.eu</dd><dt><span>data_assembly_center :</span></dt><dd>BSH</dd><dt><span>update_interval :</span></dt><dd>PT1H</dd><dt><span>citation :</span></dt><dd>These data were collected and made freely available by the Copernicus project and the programs that contribute to it</dd><dt><span>distribution_statement :</span></dt><dd>These data follow Copernicus standards; they are public and free of charge. User assumes all risk for use of data. User must display citation in any publication or product using data. User must contact PI prior to any commercial use of data.</dd><dt><span>doi :</span></dt><dd></dd><dt><span>pi_name :</span></dt><dd></dd><dt><span>qc_manual :</span></dt><dd>OceanSITES User's Manual v1.2</dd><dt><span>date_update :</span></dt><dd>2022-10-07T05:39:40Z</dd><dt><span>history :</span></dt><dd>2022-10-01T18:04:25Z : Creation; 2022-10-07T05:39:40Z, BSH North West Shelf PU: Monthly subset 202209 extracted from history file NO_TS_MO_FINO1.nc</dd><dt><span>wmo_inst_type :</span></dt><dd></dd></dl></div></li></ul></div></div>
</div>
</div>
<div class="cell" data-execution_count="64">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> fino[[<span class="st">'VHM0'</span>,<span class="st">'VTZA'</span>,<span class="st">'VPED'</span>]].isel(DEPTH<span class="op">=</span><span class="dv">0</span>).to_dataframe()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The data are stored on the concurrent timesteps.</p>
<div class="cell" data-execution_count="71">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>df[[<span class="st">'VHM0'</span>,<span class="st">'VTZA'</span>,<span class="st">'VPED'</span>]].head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="71">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>VHM0</th>
      <th>VTZA</th>
      <th>VPED</th>
    </tr>
    <tr>
      <th>TIME</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>2022-09-01 00:00:00</th>
      <td>NaN</td>
      <td>4.12</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>2022-09-01 00:02:00</th>
      <td>1.11</td>
      <td>NaN</td>
      <td>2.800000</td>
    </tr>
    <tr>
      <th>2022-09-01 00:30:00</th>
      <td>NaN</td>
      <td>4.18</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>2022-09-01 00:32:00</th>
      <td>1.09</td>
      <td>NaN</td>
      <td>353.000017</td>
    </tr>
    <tr>
      <th>2022-09-01 01:00:00</th>
      <td>NaN</td>
      <td>4.00</td>
      <td>NaN</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<div class="cell" data-execution_count="70">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>df[[<span class="st">'VHM0'</span>,<span class="st">'VTZA'</span>]].plot(style<span class="op">=</span><span class="st">'+'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="70">
<pre><code>&lt;AxesSubplot: xlabel='TIME'&gt;</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="Dfs0_-_CMEMS_insitu_files/figure-html/cell-11-output-2.png" class="img-fluid"></p>
</div>
</div>
<p>Store the results in Dfs0 format.</p>
<div class="cell" data-execution_count="77">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>pd.Series.to_dfs0?</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div class="ansi-escaped-output">
<pre><span class="ansi-red-fg">Signature:</span>
pd<span class="ansi-blue-fg">.</span>Series<span class="ansi-blue-fg">.</span>to_dfs0<span class="ansi-blue-fg">(</span>
    self<span class="ansi-blue-fg">,</span>
    filename<span class="ansi-blue-fg">,</span>
    itemtype<span class="ansi-blue-fg">=</span><span class="ansi-green-fg">None</span><span class="ansi-blue-fg">,</span>
    unit<span class="ansi-blue-fg">=</span><span class="ansi-green-fg">None</span><span class="ansi-blue-fg">,</span>
    items<span class="ansi-blue-fg">=</span><span class="ansi-green-fg">None</span><span class="ansi-blue-fg">,</span>
    title<span class="ansi-blue-fg">=</span><span class="ansi-green-fg">None</span><span class="ansi-blue-fg">,</span>
    dtype<span class="ansi-blue-fg">=</span><span class="ansi-green-fg">None</span><span class="ansi-blue-fg">,</span>
<span class="ansi-blue-fg">)</span>
<span class="ansi-red-fg">Docstring:</span> &lt;no docstring&gt;
<span class="ansi-red-fg">File:</span>      ~/mambaforge/lib/python3.10/site-packages/mikeio/dfs0.py
<span class="ansi-red-fg">Type:</span>      function
</pre>
</div>
</div>
</div>
<div class="cell" data-execution_count="78">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'VHM0'</span>].dropna().to_dfs0(<span class="st">"FINO1_VHM0.dfs0"</span>, itemtype<span class="op">=</span>mikeio.EUMType.Significant_wave_height)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Read the file again to check…</p>
<div class="cell" data-execution_count="80">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>ds <span class="op">=</span> mikeio.read(<span class="st">"FINO1_VHM0.dfs0"</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>ds</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="80">
<pre><code>&lt;mikeio.Dataset&gt;
dims: (time:1439)
time: 2022-09-01 00:02:00 - 2022-09-30 23:32:00 (1439 non-equidistant records)
items:
  0:  VHM0 &lt;Significant wave height&gt; (meter)</code></pre>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>